### ISSUE TITLE
Non-deterministic rendering in fast renderer

### ISSUE THREAD

**Issue by kabiroberai** [raspu/Highlightr#51]
When rendering nested classes, the fast renderer determines which style takes precedence in a non-deterministic manner.

Eg.
`xcode.css` has the following definitions (simplified here for the sake of brevity):
```css
.hljs-title {
  color: blue;
}

.hljs-class .hljs-title {
  color: purple;
}
```

The following JS snippet
```js
class Foo
```
is converted to
```html
<span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">Foo</span></span>
```

In the aforementioned snippet, `Foo` should turn purple, however in reality the renderer randomly picks between blue and purple, and the color it picks varies between app launches.
